fail_fast: false
exclude: |
    (?x)^(
        .venv/.*
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: local
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff linting
        args: [ --fix ]
        entry: poetry run ruff check
        language: system
        types: [python]
      # Run the formatter.
      - id: ruff-format
        name: ruff formatting
        entry: poetry run ruff format
        language: system
        types: [python]
